"""Send the output (question + top 3 contents) to other agents on the network over plain HTTP.

``WEB_SEARCH_VERIFIER_PATH=/verify,/synthesize`` lists POST routes. Every machine of this machine's subnet(s) is
probed on ``WEB_SEARCH_VERIFIER_PORT`` (8203; or a list) in parallel - one shared scan, 2 s connect timeout, 2 tries
per machine, so a flapping Wi-Fi link is still found. For each machine that answers, the listed routes it has are
looked up in its OpenAPI spec (``GET /openapi.json``, generated by FastAPI / langgraph dev), or, without a spec, by
a GET on each route (405 = POST-only route exists). The output is POSTed to every route found, in parallel:
``http://192.168.1.25:8203/verify``, ``http://192.168.1.33:8203/synthesize``, ...

The found routes are reused for ``WEB_SEARCH_DISCOVERY_TTL_SECONDS``; when a POST fails with a connection error (after
``WEB_SEARCH_SEND_ATTEMPTS`` tries) or 404/405, the network is searched again once.

One body for every route, so each agent reads the part it expects:
``{"task": AgentTask, "question": <question>, "inputs": {"web_search": <output>}}`` - ``task`` is what the orchestrator
would give the verifier (``task.inputs`` holds the output), ``question`` / ``inputs`` is the synthesizer's input format.
"""

from __future__ import annotations

import asyncio
import ipaddress
import logging
import socket
import time
from urllib.parse import urlsplit

import httpx

from utils import AgentTask
from web_search_agent.services.resources import http_client
from web_search_agent.settings import get_settings

logger = logging.getLogger(__name__)

MAX_HOSTS = 4096  # never probe more than this many addresses (e.g. a wrongly configured /16)
_SCAN_CONCURRENCY = 256
SHARED_SCAN_SECONDS = 30  # how long one scan's open hosts are reused
HTTP_ATTEMPTS = 2  # route lookups (GET) on a flapping link

_found: dict = {}  # {"urls": [...], "at": time} - the routes found on the network (cache)
_open: dict[int, dict] = {}  # port -> {"hosts": [...], "at": time, "scanned": n}: one scan shared by all lookups
_locks: dict[tuple[str, int], asyncio.Lock] = {}  # per purpose and event loop (a Lock belongs to its loop)


class TargetNotFound(RuntimeError):
    pass


def _lock(name: str) -> asyncio.Lock:
    return _locks.setdefault((name, id(asyncio.get_running_loop())), asyncio.Lock())


def body(step_id: str, result: dict) -> dict:
    """One body for every route: the verifier reads ``task``, the synthesizer ``question`` + ``inputs``."""
    task = AgentTask(task_id=f"verify-{step_id}", objective=f"Verify the web search results for: {result['question']}",
                     inputs={step_id: result})
    return {"task": task.model_dump(), "question": result["question"], "inputs": {"web_search": result}}


def _norm(path: str) -> str:
    return "/" + path.strip().strip("/").lower()


# --- which of the routes a server has ------------------------------------------------------------
async def _get(url: str, timeout: float) -> httpx.Response | None:
    """GET, retried once on a connection error (flapping link). None if it cannot be reached."""
    for attempt in range(HTTP_ATTEMPTS):
        try:
            return await http_client().get(url, timeout=httpx.Timeout(timeout, connect=3.0))
        except httpx.TransportError:
            if attempt + 1 < HTTP_ATTEMPTS:
                await asyncio.sleep(0.3)
    return None


def post_routes(spec: object) -> dict[str, str]:
    """The POST routes of an OpenAPI spec: normalised path -> path as the server spells it."""
    paths = spec.get("paths") if isinstance(spec, dict) else None
    if not isinstance(paths, dict):
        return {}
    return {_norm(p): p for p, ops in paths.items() if isinstance(ops, dict) and "post" in ops and "{" not in p}


async def routes_on(base: str, wanted: list[str]) -> list[str]:
    """Which of the ``wanted`` POST routes the server at ``base`` has (spelled as the server spells them)."""
    response = await _get(f"{base}/openapi.json", 5.0)
    try:
        spec = response.json() if response is not None and response.status_code == 200 else None
    except ValueError:
        spec = None
    if isinstance(spec, dict) and "paths" in spec:
        available = post_routes(spec)
        return [available[_norm(p)] for p in wanted if _norm(p) in available]
    found = []
    for path in wanted:  # no spec: a POST-only route answers 405 to a GET, a server without it 404
        probe = await _get(base + path, 3.0)
        if probe is not None and probe.status_code == 405:
            found.append(path)
    return found


# --- the network -------------------------------------------------------------------------------
def local_ipv4() -> list[str]:
    """This machine's IPv4 addresses (primary interface first), without loopback / link-local. Blocking."""
    found: list[str] = []
    try:  # the interface that routes to the LAN; UDP connect sends no packet
        with socket.socket(socket.AF_INET, socket.SOCK_DGRAM) as sock:
            sock.connect(("10.255.255.255", 1))
            found.append(sock.getsockname()[0])
    except OSError:
        pass
    try:
        found += [info[4][0] for info in socket.getaddrinfo(socket.gethostname(), None, socket.AF_INET)]
    except OSError:
        pass
    usable = []
    for ip in dict.fromkeys(found):
        address = ipaddress.ip_address(ip)
        if not (address.is_loopback or address.is_link_local or address.is_unspecified):
            usable.append(ip)
    return usable


def networks() -> list[ipaddress.IPv4Network]:
    """``WEB_SEARCH_DISCOVERY_SUBNETS`` (e.g. ``192.168.1.0/24``), else the /24 of each local address. Blocking."""
    configured = get_settings().discovery_subnets
    if configured:
        return [ipaddress.ip_network(n.strip(), strict=False) for n in configured.split(",") if n.strip()]
    return list(dict.fromkeys(ipaddress.ip_network(f"{ip}/24", strict=False) for ip in local_ipv4()))


def candidate_hosts() -> list[str]:
    """Other machines of the network(s) first, this machine last. Blocking."""
    own = set(local_ipv4())
    hosts: list[str] = []
    for network in networks():
        hosts += [str(h) for h in network.hosts() if str(h) not in own]
    hosts = list(dict.fromkeys(hosts))[:MAX_HOSTS]
    return hosts + sorted(own) + ["127.0.0.1"]


async def _port_open(host: str, port: int, timeout: float) -> bool:
    try:
        _, writer = await asyncio.wait_for(asyncio.open_connection(host, port), timeout)
    except (OSError, TimeoutError):
        return False
    writer.close()
    try:
        await writer.wait_closed()
    except OSError:
        pass
    return True


async def open_hosts(port: int) -> list[str]:
    """Hosts listening on ``port`` (other machines first). One scan per port, reused for a short time."""
    cached = _open.get(port)
    if cached and time.time() - cached["at"] < SHARED_SCAN_SECONDS:
        return cached["hosts"]
    async with _lock(f"scan:{port}"):
        cached = _open.get(port)
        if cached and time.time() - cached["at"] < SHARED_SCAN_SECONDS:
            return cached["hosts"]
        settings = get_settings()
        timeout, attempts = settings.discovery_scan_timeout_seconds, max(1, settings.discovery_attempts)
        # Reading this machine's addresses uses blocking socket calls: keep them off the event loop.
        hosts = await asyncio.to_thread(candidate_hosts)
        own = set(await asyncio.to_thread(local_ipv4)) | {"127.0.0.1"}
        semaphore = asyncio.Semaphore(_SCAN_CONCURRENCY)

        async def probe(host: str) -> str | None:
            async with semaphore:
                for _ in range(attempts):  # a flapping link answers only some of the time
                    if await _port_open(host, port, timeout):
                        return host
                return None

        found = [h for h in await asyncio.gather(*(probe(h) for h in hosts)) if h]
        # this machine answers on its LAN address and on 127.0.0.1: keep it once
        mine = [h for h in found if h in own]
        found = [h for h in found if h not in own] + mine[:1]
        _open[port] = {"hosts": found, "at": time.time(), "scanned": len(hosts)}
        return found


async def discover() -> list[str]:
    """Every configured route on every machine of the network that has it. Cached."""
    settings = get_settings()
    wanted = settings.output_paths
    started = time.time()
    bases = [f"http://{h}:{port}" for port in settings.output_ports for h in await open_hosts(port)]
    per_base = await asyncio.gather(*(routes_on(b, wanted) for b in bases))
    urls = [b + path for b, paths in zip(bases, per_base, strict=True) for path in paths]
    logger.info("output routes %s: machines on port %s: %s -> found %s (%.1f s)", wanted,
                ",".join(map(str, settings.output_ports)), [b.split("//")[1] for b in bases] or "none",
                urls or "none", time.time() - started)
    _found.update(urls=urls, at=time.time())
    return urls


def _fresh() -> bool:
    return bool(_found.get("urls")) and time.time() - _found["at"] < get_settings().discovery_ttl_seconds


async def endpoints(refresh: bool = False) -> list[str]:
    """The URLs to send the output to (found on the network). Raises TargetNotFound if there are none."""
    settings = get_settings()
    if not settings.output_paths:
        return []
    if refresh:
        _open.clear()
    if refresh or not _fresh():
        async with _lock("discover"):
            if refresh or not _fresh():
                await discover()
    urls = _found.get("urls") or []
    if not urls:
        where = ", ".join(str(n) for n in await asyncio.to_thread(networks)) or "no network found"
        ports = ",".join(map(str, settings.output_ports))
        raise TargetNotFound(f"no machine with {', '.join(settings.output_paths)} on port {ports} in {where}")
    return urls


def discovered() -> dict:
    """For /custom/health."""
    return {"urls": list(_found.get("urls") or []),
            "age_s": round(time.time() - _found["at"], 1) if _found.get("at") else None}


# --- sending ------------------------------------------------------------------------------------
async def _post(url: str, payload: dict) -> httpx.Response:
    """POST, retried on connection errors (a flapping link): WEB_SEARCH_SEND_ATTEMPTS tries, short pauses."""
    settings = get_settings()
    headers = {"Authorization": f"Bearer {settings.verifier_token}"} if settings.verifier_token else None
    attempts = max(1, settings.send_attempts)
    for attempt in range(1, attempts + 1):
        try:
            return await http_client().post(url, json=payload, headers=headers,
                                            timeout=httpx.Timeout(settings.verifier_timeout_seconds, connect=5.0))
        except (httpx.ConnectError, httpx.ConnectTimeout):
            if attempt == attempts:
                raise
            logger.info("connection to %s failed (try %d/%d), retrying", url, attempt, attempts)
            await asyncio.sleep(0.5 * attempt)
    raise AssertionError("unreachable")


async def send_to(url: str, payload: dict) -> dict:
    """POST the payload; returns the response (``{"result": {...}}`` unwrapped)."""
    response = await _post(url, payload)
    response.raise_for_status()
    data = response.json()
    if not isinstance(data, dict):
        return {"response": data}
    return data["result"] if isinstance(data.get("result"), dict) else data


def _routing_error(exc: Exception) -> bool:
    if isinstance(exc, httpx.HTTPStatusError):
        return exc.response.status_code in (404, 405)
    return isinstance(exc, httpx.TransportError | OSError)


def _record(url: str, response: dict | None = None, error: Exception | None = None) -> dict:
    parts = urlsplit(url)
    record: dict = {"url": url, "path": parts.path, "host": parts.hostname}
    if error is not None:
        return {**record, "status": "failed", "error": f"{type(error).__name__}: {error}"[:300]}
    record.update(status="sent", response=response)
    if isinstance(response, dict) and "passed" in response:  # a verifier's verdict
        record.update(passed=response.get("passed"), issues=response.get("issues", []),
                      warnings=response.get("warnings", []), summary=response.get("summary", ""))
    return record


async def deliver(step_id: str, result: dict) -> list[dict]:
    """Send the output to every route found. One record per URL: status sent/failed, response, verdict fields.

    Raises TargetNotFound when no route is found on the network at all.
    """
    payload = body(step_id, result)
    urls = await endpoints()

    async def one(url: str) -> dict:
        try:
            return _record(url, await send_to(url, payload))
        except Exception as exc:  # noqa: BLE001 - reported per URL
            return _record(url, error=exc) | {"_routing": _routing_error(exc)}

    records = list(await asyncio.gather(*(one(u) for u in urls)))
    routing = [r.pop("_routing", False) for r in records]
    if any(routing):
        # A machine moved, restarted or changed its routes: search the network again once, retry what is new/failed.
        sent = {r["url"] for r in records if r["status"] == "sent"}
        try:
            fresh = await endpoints(refresh=True)
        except TargetNotFound:
            fresh = []
        retried = {r["url"]: r for r in await asyncio.gather(*(one(u) for u in fresh if u not in sent))}
        for r in retried.values():
            r.pop("_routing", None)
        records = [r for r in records if r["url"] not in retried] + list(retried.values())
    return records


async def reachable() -> dict:
    """For /custom/health: the routes found now (a network search if none are cached)."""
    try:
        return {"urls": await endpoints(), "error": None}
    except TargetNotFound as exc:
        return {"urls": [], "error": str(exc)}
